services:
    sonata.media.provider.webcam:
        class: Anacona16\Bundle\SonataMediaWebcamProviderBundle\SonataMedia\Provider\WebcamProvider
        parent: sonata.media.provider.image
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: sonata.media.provider }
