services:
    sonata.media.provider.webcam:
        class: Anacona16\Bundle\SonataMediaWebcamProviderBundle\SonataMedia\Provider\WebcamProvider
        parent: sonata.media.provider.image
        calls:
            - [setTwig, ['@twig']]
        tags:
            - { name: sonata.media.provider }
